services:
  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"
    env_file:
      - .env.local

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
    env_file:
      - .env.local

  frontend:
    build: .
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - .env.local
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
